{
 "title": "New dashboard - Test 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_histogram_count{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "[{{method}}] {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (sum by(path, method, status) (rate(http_request_histogram_bucket{status=~\"400\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (sum by(path, method, status) (rate(http_request_histogram_bucket{status=\"500\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_histogram_bucket{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "[{{method}}] - {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_histogram_bucket{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "[{{method}}] - {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_histogram_bucket{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{method}} - {{path}} - {{status}}"
    }
   ]
  }
 ]
}